/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 scene.gltf 
Author: Every 3D (https://sketchfab.com/Every_3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/animation-flags-let-there-be-peace-50b708e248be4235b1f72ec4cceab9a8
Title: Animation flags | Let there be peace | Я за мир!
*/

import React from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Korea(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF("/models/Korea/scene.gltf");
  const { actions } = useAnimations(animations, group);
  return (
    <group
      ref={group}
      rotation={[Math.PI, Math.PI / 2, Math.PI]}
      {...props}
      dispose={null}
    >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="03dec5fc680e4ccca21cb0afb6b611a4abccleanermaterialmergergles">
            <group name="Object_2" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Object_3">
                <group name="Object_4" position={[3, 0, 0]}>
                  <group name="MorphMainGroup">
                    <mesh
                      name="Plane_002"
                      geometry={nodes.Plane_002.geometry}
                      material={materials.Plane_002}
                      morphTargetDictionary={
                        nodes.Plane_002.morphTargetDictionary
                      }
                      morphTargetInfluences={
                        nodes.Plane_002.morphTargetInfluences
                      }
                    />
                  </group>
                </group>
                <group name="Object_21" position={[3, 0, 0]}>
                  <group name="TimeframeMainGroup_2">
                    <group name="Object_23">
                      <mesh
                        name="Cylinder_002_12_0"
                        geometry={nodes.Cylinder_002_12_0.geometry}
                        material={materials.Cylinder_002}
                      />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
